apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-profile-deployment
  labels:
    app: spring-profile
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-profile
  template:
    metadata:
      labels:
        app: spring-profile
    spec:
      containers:
      - name: spring-profile-container
        image: us-east1-docker.pkg.dev/gcp-docker-kubernetes-486700/profile-service/clouduser/profile-service:0.1.0
        ports:
        - containerPort: 8080
