apiVersion: v1
kind: Secret
metadata:
  name: profile-secret
type: Opaque
data:
  # TODO: update mysql-username and mysql-password to match the variables that you used
  # to authenticate into the MySQL service. These should be provided in base64 encoded form.
  mysql-username: 'eGlhbnF1YXk='
  mysql-password: 'NTAxMjEyNTE5OTFWaQ=='
