apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: profile-ingress
spec:
  ingressClassName: profile-nginx
  rules:
  - http:
      paths:
      - path: /chat
        pathType: exact
        backend:
          service:
            name: spring-chat-service
            port:
              number: 80
      - path: /login
        pathType: exact
        backend:
          service:
            name: spring-login-service
            port:
              number: 80
      - path: /profile
        pathType: exact
        backend:
          service:
            name: spring-profile-service
            port:
              number: 80                            
