weCloud:
  imageRegistry:
    gcp: us-east1-docker.pkg.dev/gcp-docker-kubernetes-486700 

profile:
  releaseName: "spring-profile"
  replicaCount: 3
  repository: profile-service
  image: clouduser/profile-service
  tag: "0.0.1"
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080
  mysql:
    host: "mysql-profile.default.svc.cluster.local"
    secretName: "profile-secret"
    user: "mysql-username"
    password: "mysql-password"
    port: "3306"
