apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.login.releaseName }}-deployment
  labels:
    app: {{ .Values.login.releaseName }}
spec:
  replicas: {{ .Values.login.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.login.releaseName }}
  template:
    metadata:
      labels:
        app: {{ .Values.login.releaseName }}
    spec:
      containers:
      - name: {{ .Values.login.releaseName }}-container
        image: {{ .Values.weCloud.imageRegistry.gcp }}/{{ .Values.login.repository }}/{{ .Values.login.image }}:{{ .Values.login.tag }}
        ports:
        - containerPort: 8080
        env:
          - name: MYSQL_DB_HOST
            value: {{ .Values.login.mysql.host | quote }}
          - name: MYSQL_DB_PORT
            value: {{ .Values.login.mysql.port | quote }}
          - name: MYSQL_DB_USER
            valueFrom:
              secretKeyRef:
                name: login-secret
                key: mysql-username
          - name: MYSQL_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: login-secret
                key: mysql-password
          - name: LIST_OF_CHAT_ENDPOINTS
            value: {{ .Values.login.chatEndpoints | quote }}