weCloud:
  imageRegistry:
    gcp: us-east1-docker.pkg.dev/gcp-docker-kubernetes-486700 

profile:
  releaseName: "spring-profile"
  replicaCount: 3
  repository: profile-service
  image: clouduser/profile-service
  tag: "0.0.1"
  service:
    type: NodePort
    port: 80
    targetPort: 8080
  mysql:
    host: "mysql-profile.default.svc.cluster.local"
    secretName: "profile-secret"
    user: "mysql-username"
    password: "mysql-password"
    port: "3306"


chat:
  profileEndpoints: "spring-profile-service.default.svc.cluster.local" 
  releaseName: "spring-chat"
  replicaCount: 3
  repository: profile-service
  image: clouduser/chat-service
  tag: "0.0.1"
  service:
    type: NodePort
    port: 80
    targetPort: 8080
  mysql:
    host: "mysql-chat.default.svc.cluster.local"
    secretName: "chat-secret"
    user: "mysql-username"
    password: "mysql-password"
    port: "3306"

login:
  chatEndpoints: "http://104.196.104.107"
  releaseName: "spring-login"
  replicaCount: 3
  repository: profile-service
  image: clouduser/login-service
  tag: "0.0.1"
  service:
    type: NodePort
    port: 80
    targetPort: 8080
  mysql:
    host: "mysql-login.default.svc.cluster.local"
    secretName: "login-secret"
    user: "mysql-username"
    password: "mysql-password"
    port: "3306"

# Below are the values used in the redis service
# DO NOT MODIFY
redis:
  image: "redis:7"
  host: "redis-service"
  password: "SuperSecretRedisPassword"
  passwordSecret: "redis-secret"
  passwordKey: "REDIS_PASSWORD"
  port: "6379"
  containerPort: 6379
  topic: "/topic/messages"
  service:
    port: 6379
    targetPort: 6379