apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.chat.releaseName }}-deployment
  labels:
    app: {{ .Values.chat.releaseName }}
spec:
  replicas: {{ .Values.chat.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.chat.releaseName }}
  template:
    metadata:
      labels:
        app: {{ .Values.chat.releaseName }}
    spec:
      containers:
      - name: {{ .Values.chat.releaseName }}-container
        image: {{ .Values.weCloud.imageRegistry.gcp }}/{{ .Values.chat.repository }}/{{ .Values.chat.image }}:{{ .Values.chat.tag }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
        env:
          - name: MYSQL_DB_HOST
            value: {{ .Values.chat.mysql.host | quote }}
          - name: MYSQL_DB_PORT
            value: {{ .Values.chat.mysql.port | quote }}
          - name: MYSQL_DB_USER
            valueFrom:
              secretKeyRef:
                name: chat-secret
                key: mysql-username
          - name: MYSQL_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: chat-secret
                key: mysql-password
          - name: SPRING_REDIS_HOST
            value: {{ .Values.redis.host | quote }}
          - name: SPRING_REDIS_PORT
            value: {{ .Values.redis.port | quote }}
          - name: SPRING_REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.redis.passwordSecret }}
                key: {{ .Values.redis.passwordKey }}
          - name: LIST_OF_PROFILE_ENDPOINTS
            value: {{ .Values.chat.profileEndpoints | quote }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-profile-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.chat.releaseName }}-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
