apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.login.releaseName }}-deployment
  labels:
    app: {{ .Values.login.releaseName }}
spec:
  replicas: {{ .Values.login.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.login.releaseName }}
  template:
    metadata:
      labels:
        app: {{ .Values.login.releaseName }}
    spec:
      containers:
      - name: {{ .Values.login.releaseName }}-container

        {{- if eq .Values.global.environment "gcp" }}
        image: {{ .Values.global.imageRegistry }}/{{ .Values.login.imageRepo }}/{{ .Values.login.imageName }}:{{ .Values.login.tag }}
        {{- else if eq .Values.global.environment "azure" }}
        image: {{ .Values.global.imageRegistry }}/{{ .Values.login.imageName }}:{{ .Values.login.tag }}
        {{- end }}

        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
        env:
          - name: MYSQL_DB_HOST
            value: {{ .Values.login.mysql.host | quote }}
          - name: MYSQL_DB_PORT
            value: {{ .Values.login.mysql.port | quote }}
          - name: MYSQL_DB_USER
            valueFrom:
              secretKeyRef:
                name: login-secret
                key: mysql-username
          - name: MYSQL_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: login-secret
                key: mysql-password
          - name: CHAT_ENDPOINT
            value: {{ .Values.login.chatEndpoints | quote }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-login-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.login.releaseName }}-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50            