global:
  environment: azure
  imageRegistry: "wecloudacr1.azurecr.io"
  ingressClassName: "webapprouting.kubernetes.azure.com"   

login:
  imageName: "clouduser/login-service"
  tag: "1.1.0"
  mysql:
    host: "mysql-profile.default.svc.cluster.local"
    secretName: "profile-secret"
    user: "mysql-username"
    password: "mysql-password"
    port: "3306"
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
    cpuRequest: 200m

profile:
  imageName: "clouduser/profile-service"
  tag: "1.1.0"
  mysql:
    host: "mysql-profile.default.svc.cluster.local"
    secretName: "profile-secret"
    user: "mysql-username"
    password: "mysql-password"
    port: "3306"
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
    cpuRequest: 200m
